<a href="https://colab.research.google.com/github/tamayzengin/Machine-learning-algorhythms/blob/main/notebooks/regularization_methods_ipynb_adl%C4%B1_dosyan%C4%B1n_kopyas%C4%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Libraries**

In [ ]:
import numpy as np
import pandas as pd 
import sklearn as sk
import matplotlib.pyplot as plt
import seaborn as sns

# **L2 Regularization**

In [ ]:
cd /content/drive/MyDrive/Colab Notebooks/DATA

/content/drive/MyDrive/Colab Notebooks/DATA


In [ ]:
df = pd.read_csv('Advertising.csv')

In [ ]:
X = df.drop(['sales'],axis=1)

In [ ]:
y = df['sales']

In [ ]:
from sklearn.preprocessing import  PolynomialFeatures

In [ ]:
polinomial_converter = PolynomialFeatures(degree=3, include_bias=False)

In [ ]:
poly_features= polinomial_converter.fit_transform(X)

In [ ]:
X.shape

(200, 3)

In [ ]:
poly_features.shape

(200, 19)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

In [ ]:
scaler.fit(X_train)

StandardScaler()

In [ ]:
X_train = scaler.transform(X_train)

In [ ]:
X_test = scaler.transform(X_test)

In [ ]:
X_train[0] #poly_featurs'a göre Sayılar azaldı

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [ ]:
poly_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

#**Ridge Regression**


In [ ]:
# ERROR = RSS + Penalty term, we're trying to minimize this error penalty (sum all B^2)*lambda

In [ ]:
from sklearn.linear_model import Ridge

In [ ]:
ridge_model = Ridge(alpha=10)

In [ ]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [ ]:
test_predictions = ridge_model.predict(X_test)

In [ ]:
test_predictions

array([13.7469803 , 19.17764   , 11.8623393 , 16.25574551,  8.92891155,
        8.04595366, 20.13320851, 16.94847676, 10.29219174, 19.78365691,
       10.31758361, 13.44077317, 12.24228062, 23.23864236, 19.12656362,
        9.748809  , 12.84361521,  9.14248129,  8.82504966, 21.46989971,
        8.25222201, 18.8110776 , 28.39227333, 25.06911066,  9.11912241,
       11.8071711 , 20.85199462,  9.31962495, 12.25122303,  9.07811198,
        9.25275556, 19.87154568, 10.55955497,  7.86818084, 17.67220132,
        9.31442423, 10.1539168 ,  9.47802944,  8.63337302, 10.76209179,
       11.63848891, 10.38883411, 10.90270005,  8.40019284, 11.35336224,
       10.3514086 ,  8.00082147, 15.27139854, 12.94761469, 22.49762978,
       10.80165407, 13.01337743, 14.82204895, 11.37354043, 11.69628953,
        7.20576885, 25.53512232, 10.41926545, 17.38798022, 15.10158819])

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [ ]:
MAE = mean_absolute_error(y_test,test_predictions)

In [ ]:
MAE

0.5774404204714162

In [ ]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [ ]:
from sklearn.linear_model import RidgeCV

In [ ]:
ridge_cv_model = RidgeCV(alphas=(0.1,1.0,10.0),scoring='neg_mean_absolute_error')

In [ ]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_absolute_error')

In [ ]:
ridge_cv_model.alpha_

0.1

In [ ]:
#from sklearn.metrics import SCORERS

In [ ]:
#SCORERS.keys()

In [ ]:
test_predictions = ridge_cv_model.predict(X_test)

In [ ]:
MAE = mean_absolute_error(y_test,test_predictions)

In [ ]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [ ]:
MAE 

0.4273774884345441

In [ ]:
RMSE

0.6180719926946004

In [ ]:
ridge_cv_model.best_score_

-0.3749223340292962

#**L1 regularization**
Lasso Regression



In [ ]:
from sklearn.linear_model import LassoCV

In [ ]:
lasso_cv_model = LassoCV(eps=0.001,n_alphas=100,cv=5,max_iter=1000000) #eps değeri küçük(0.001) olursa taranan alan küçülür. Bu yüzden COnvergenceWarning uyarısı verilir. Taranmayan veriler old. anlamına gelir. eps=0.1 olmalı.

In [ ]:
lasso_cv_model.fit(X_train,y_train) 

LassoCV(cv=5, max_iter=1000000)

In [ ]:
lasso_cv_model.alpha_

0.004943070909225833

In [ ]:
test_predictions = lasso_cv_model.predict(X_test)

In [ ]:
MAE = mean_absolute_error(y_test,test_predictions)

In [ ]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [ ]:
MAE

0.4335034618590078

In [ ]:
RMSE

0.6063140748984043

In [ ]:
lasso_cv_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

**Lasso ile ilgili not: Bütün polynomial set yerine, setin bir kısımını inceler. Bu sette TV ve radyo gibi. Daha kötü bir sonuç verir fakat çok daha az veri tarar **

#**L1 And L2 Regularization - Elastic Net** 

Elastic Net regression, l1_ratio ve l2_ratiolar ile hem lasso hem de Ridge regressionları kendi içinde barındırır.

In [ ]:
from sklearn.linear_model import ElasticNetCV

In [ ]:
elastic_model = ElasticNetCV(l1_ratio=[.1,.5,.7,.9,.95,.99,1],eps=0.001,n_alphas=100,max_iter=1000000)

In [ ]:
elastic_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [ ]:
elastic_model.l1_ratio

[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1]

In [ ]:
elastic_model.l1_ratio_ #En iyi değeri döndürür

1.0

In [ ]:
elastic_model.alpha_ # Lasso ile aynı

0.004943070909225833

In [ ]:
lasso_cv_model.alpha_

0.004943070909225833

In [ ]:
test_predictions = elastic_model.predict(X_test)

In [ ]:
MAE = mean_absolute_error(y_test,test_predictions)

In [ ]:
MAE # Lasso ile aynı

0.4335034618590078

#**Train test split Review**

In [ ]:
X = df.drop('sales',axis=1)

In [ ]:
y = df['sales']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler =  StandardScaler() 

In [ ]:
scaler.fit(X_train)

StandardScaler()

In [ ]:
X_train = scaler.transform(X_train)

In [ ]:
X_test = scaler.transform(X_test)

In [ ]:
from sklearn.linear_model import Ridge

In [ ]:
model = Ridge(alpha=100)

In [ ]:
model.fit(X_train,y_train)

Ridge(alpha=100)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
mean_squared_error(y_test,y_pred)

7.34177578903413

In [ ]:
model_two = Ridge(alpha=1)
model_two.fit(X_train,y_train)
y_pred_two = model_two.predict(X_test)

In [ ]:
mean_squared_error(y_test,y_pred_two)

2.319021579428752

Simple Train Test Split
Advantages:
1.  easy to understand and it's easy to compute 
*   Disadvantages:
1.  To find Optimal hyperparameter it's tedious
2.  Major issue is; when trying to find optimal hyperparameter, you try models,(one,two etc.) thus model do see the datas beforeward 
